In [1]:
#Question 1
import numpy as np 
ls=[1,2,3,4,5]
arr=np.array(ls)
#Part 1
arr+=2
print(arr)
#Part 2
arr*=3
print(arr)
#Part 3
arr=arr/2
print(arr)

[3 4 5 6 7]
[ 9 12 15 18 21]
[ 4.5  6.   7.5  9.  10.5]


In [2]:
#Question 2
ls=[1,2,3,6,5,4]
arr=np.array(ls)
#Part 1
print(arr)
print(arr[::-1])
#Part 2
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_frequent_value = np.bincount(x).argmax()
indices = np.where(x == most_frequent_value)[0]
print(x)
print(most_frequent_value)
#Part 3
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, 3])
print(y)
most_frequent_value = np.bincount(y).argmax()
indices = np.where(y== most_frequent_value)[0]
print(most_frequent_value)

[1 2 3 6 5 4]
[4 5 6 3 2 1]
[1 2 3 4 5 1 2 1 1 1]
1
[1 1 1 2 3 4 2 4 3 3 3]
3


In [3]:
#Question 3
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print(arr[0][1])
print(arr[2][0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
20
70


In [4]:
#Question 4
name_array = np.linspace(10, 100, 25)

# Print properties of the array
print("\nQ4 Results:")
print("Dimensions:", name_array.ndim)
print("Shape:", name_array.shape)
print("Total Elements:", name_array.size)
print("Data Type:", name_array.dtype)
print("Bytes Consumed:", name_array.nbytes)

# Transpose using reshape
reshaped_array = name_array.reshape(5, 5).T
print("Reshaped Transposed Array:\n", reshaped_array)

# Checking if T attribute works (Yes, it does)
print("Transpose using .T:\n", name_array.reshape(5, 5).T)


Q4 Results:
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Bytes Consumed: 200
Reshaped Transposed Array:
 [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]
Transpose using .T:
 [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


In [5]:
#Question 5
ucs420_name = np.array([[10, 20, 30, 40], 
                        [50, 60, 70, 80], 
                        [90, 15, 20, 35]])

# Compute statistics
mean_value = np.mean(ucs420_name)
median_value = np.median(ucs420_name)
max_value = np.max(ucs420_name)
min_value = np.min(ucs420_name)
unique_values = np.unique(ucs420_name)

print("\nQ5 Results:")
print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_values)

# Reshape and Resize
reshaped_ucs420 = ucs420_name.reshape(4, 3)
resized_ucs420 = ucs420_name[:2, :3]  # Resize to 2x3

print("Reshaped Array (4x3):\n", reshaped_ucs420)
print("Resized Array (2x3):\n", resized_ucs420)


Q5 Results:
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [50 60 70]]
